#!/bin/sh

set -eu

# self update
cp extra/post-receive .git/hooks/post-receive
chmod +x .git/hooks/post-receive

# Use local n
PATH=$HOME/n/bin:$PATH

# update deps
yarn

# restart (lol)
killall node
