#!/bin/sh

set -eu

# self update
cp extra/post-receive .git/hooks/post-receive
chmod +x .git/hooks/post-receive

# Use local n
PATH=$HOME/n/bin:$PATH

# update deps, bundles and prerenders
make

# restart (lol)
killall node
